FROM node:12.2.0-alpine as build
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ARG REACT_APP_API_URL
ARG REACT_APP_MYDASH_CLIENT_ID
ARG REACT_APP_MYDASH_CONNECTION_ROUTE
ARG REACT_APP_MYDASH_REDIRECT_API
ARG REACT_APP_QCM_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_MYDASH_CLIENT_ID=$REACT_APP_MYDASH_CLIENT_ID
ENV REACT_APP_MYDASH_CONNECTION_ROUTE=$REACT_APP_MYDASH_CONNECTION_ROUTE
ENV REACT_APP_MYDASH_REDIRECT_API=$REACT_APP_MYDASH_REDIRECT_API
ENV REACT_APP_QCM_URL=$REACT_APP_QCM_URL
COPY package.json ./package.json
RUN npm install --silent
RUN npm install -g serve --silent
RUN npm install react-scripts@3.0.1 -g --silent
COPY . .
RUN npm run build

EXPOSE 80
CMD ["serve", "-s", "build", "-l", "80"]
